# Generated by Django 5.2.7 on 2025-10-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('hall_type', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Halls',
                'ordering': ['hall_type'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=15)),
                ('duration', models.TimeField()),
                ('age_rating', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.BooleanField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.hall')),
            ],
            options={
                'verbose_name_plural': 'Seats',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.customer')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Republic.showtime')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': ['status'],
            },
        ),
    ]
