# Generated by Django 5.2.7 on 2025-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['is_hall_vip'], 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['is_paid'], 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='hall_type',
            new_name='is_hall_vip',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seat_type',
            new_name='is_seat_vip',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
