# Generated by Django 5.2.8 on 2025-11-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.URLField(default='/test'),
            preserve_default=False,
        ),
    ]
