# Generated by Django 5.2.7 on 2025-11-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0004_movie_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='picture',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='null', upload_to='posters/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
