# Generated by Django 5.2.7 on 2025-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0005_remove_movie_picture_movie_poster_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
