# Generated by Django 5.2.7 on 2025-12-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0006_movie_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
