# Generated by Django 5.2.7 on 2025-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Republic', '0007_remove_showtime_hall_remove_seat_hall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='Republic.genre'),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('duration_minutes', models.IntegerField(blank=True, default=1, null=True)),
                ('age_rating', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers/')),
                ('genres', models.ManyToManyField(blank=True, related_name='tv_shows', to='Republic.genre')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['title'],
            },
        ),
    ]
